container:
  image: golang:latest

task:
  matrix:
    - name: go1.19
      script: bash *.sh
    - name: go1.18
      script: bash *.sh
    - name: go1.17
      script: bash *.sh
    - name: go1.16
      script: bash *.sh
    - name: go1.15
      script: bash *.sh
